CREATE TABLE customer
(
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    age         SMALLINT,
    gender      BOOLEAN,
    weight      FLOAT                                   NOT NULL,
    height      FLOAT                                   NOT NULL,
    goal        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);

CREATE TABLE dish
(
    dish_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title             VARCHAR(255)                            NOT NULL,
    calories_per_dish INTEGER                                 NOT NULL,
    protein           INTEGER                                 NOT NULL,
    carbohydrates     INTEGER                                 NOT NULL,
    fat               INTEGER                                 NOT NULL,
    CONSTRAINT pk_dish PRIMARY KEY (dish_id)
);

CREATE TABLE meal
(
    meal_id     BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    note        VARCHAR(255),
    CONSTRAINT pk_meal PRIMARY KEY (meal_id)
);

CREATE TABLE meals_dishes
(
    dish_id BIGINT NOT NULL,
    meal_id BIGINT NOT NULL,
    CONSTRAINT pk_meals_dishes PRIMARY KEY (dish_id, meal_id)
);

ALTER TABLE customer
    ADD CONSTRAINT uc_customer_email UNIQUE (email);

ALTER TABLE meal
    ADD CONSTRAINT FK_MEAL_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE meals_dishes
    ADD CONSTRAINT fk_meadis_on_dish FOREIGN KEY (meal_id) REFERENCES dish (dish_id);

ALTER TABLE meals_dishes
    ADD CONSTRAINT fk_meadis_on_meal FOREIGN KEY (dish_id) REFERENCES meal (meal_id);